apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud
spec:
  selector:
    matchLabels:
      app: cloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cloud
    spec:
      containers:
        - image: domaindrivenarchitecture/c4k-cloud-app
          name: cloud-app
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
          env:
            - name: NEXTCLOUD_ADMIN_USER_FILE
              value: /var/run/secrets/cloud-secrets/nextcloud-admin-user
            - name: NEXTCLOUD_ADMIN_PASSWORD_FILE
              value: /var/run/secrets/cloud-secrets/nextcloud-admin-password
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: fqdn
            - name: POSTGRES_USER_FILE
              value: /var/run/secrets/postgres-secret/postgres-user
            - name: POSTGRES_PASSWORD_FILE
              value: /var/run/secrets/postgres-secret/postgres-password
            - name: POSTGRES_DB_FILE
              value: /var/run/configs/postgres-config/postgres-db
            - name: POSTGRES_HOST
              value: "postgresql-service:5432"
          volumeMounts:
            - name: cloud-data-volume
              mountPath: /var/www/html
            - name: cloud-secret-volume
              mountPath: /var/run/secrets/cloud-secrets
              readOnly: true
            - name: postgres-secret-volume
              mountPath: /var/run/secrets/postgres-secret
              readOnly: true
            - name: postgres-config-volume
              mountPath: /var/run/configs/postgres-config
              readOnly: true
      volumes:
      - name: cloud-data-volume
        persistentVolumeClaim:
          claimName: cloud-pvc
      - name: cloud-secret-volume
        secret:
          secretName: cloud-secret
      - name: postgres-secret-volume
        secret:
          secretName: postgres-secret
      - name: postgres-config-volume
        configMap:
          name: postgres-config
          items:
            - key: postgres-db
              path: postgres-db
      - name: backup-secret-volume
        secret:
          secretName: backup-secret
