apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-pvc
  labels:
    app.kubernetes.io/application: cloud
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  selector:
    matchLabels:
      app.kubernetes.io/application: cloud
