apiVersion: v1
kind: Service
metadata:
  name: cloud-service
  labels:
    app.kubernetes.io/name: cloud-service
    app.kubernetes.io/application: cloud
spec:
  selector:
    app.kubernetes.io/name: cloud-pod
    app.kubernetes.io/application: cloud
  ports:
    - port: 80
