apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-pvc
  labels:
    app: cloud
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi